<template>
  <div class="d-icon">
    <el-icon :size="size" :color="color">
      <AddLocation v-if="props.class === 'AddLocation'" />
      <Aim v-if="props.class === 'Aim'" />
      <AlarmClock v-if="props.class === 'AlarmClock'" />
      <Apple v-if="props.class === 'Apple'" />
      <ArrowDownBold v-if="props.class === 'ArrowDownBold'" />
      <ArrowDown v-if="props.class === 'ArrowDown'" />
      <ArrowLeftBold v-if="props.class === 'ArrowLeftBold'" />
      <ArrowLeft v-if="props.class === 'ArrowLeft'" />
      <ArrowRightBold v-if="props.class === 'ArrowRightBold'" />
      <ArrowRight v-if="props.class === 'ArrowRight'" />
      <ArrowUpBold v-if="props.class === 'ArrowUpBold'" />
      <Avatar v-if="props.class === 'Avatar'" />
      <Back v-if="props.class === 'Back'" />
      <Baseball v-if="props.class === 'Baseball'" />
      <Basketball v-if="props.class === 'Basketball'" />
      <Bell v-if="props.class === 'Bell'" />
      <BellFilled v-if="props.class === 'BellFilled'" />
      <Bicycle v-if="props.class === 'Bicycle'" />
      <Bottom v-if="props.class === 'Bottom'" />
      <BottomLeft v-if="props.class === 'BottomLeft'" />
      <BottomRight v-if="props.class === 'BottomRight'" />
      <Bowl v-if="props.class === 'Bowl'" />
      <Box v-if="props.class === 'Box'" />
      <Briefcase v-if="props.class === 'Briefcase'" />
      <Brush v-if="props.class === 'Brush'" />
      <BrushFilled v-if="props.class === 'BrushFilled'" />
      <Burger v-if="props.class === 'Burger'" />
      <Calendar v-if="props.class === 'Calendar'" />
      <Camera v-if="props.class === 'Camera'" />
      <CameraFilled v-if="props.class === 'CameraFilled'" />
      <CaretBottom v-if="props.class === 'CaretBottom'" />
      <CaretLeft v-if="props.class === 'CaretLeft'" />
      <CaretRight v-if="props.class === 'CaretRight'" />
      <CaretTop v-if="props.class === 'CaretTop'" />
      <Cellphone v-if="props.class === 'Cellphone'" />
      <ChatDotRound v-if="props.class === 'ChatDotRound'" />
      <ChatDotSquare v-if="props.class === 'ChatDotSquare'" />
      <ChatLineRound v-if="props.class === 'ChatLineRound'" />
      <ChatLineSquare v-if="props.class === 'ChatLineSquare'" />
      <ChatRound v-if="props.class === 'ChatRound'" />
      <ChatSquare v-if="props.class === 'ChatSquare'" />
      <Check v-if="props.class === 'Check'" />
      <Checked v-if="props.class === 'Checked'" />
      <Cherry v-if="props.class === 'Cherry'" />
      <Chicken v-if="props.class === 'Chicken'" />
      <CircleCheck v-if="props.class === 'CircleCheck'" />
      <CircleCheckFilled v-if="props.class === 'CircleCheckFilled'" />
      <CircleClose v-if="props.class === 'CircleClose'" />
      <CircleCloseFilled v-if="props.class === 'CircleCloseFilled'" />
      <CirclePlus v-if="props.class === 'CirclePlus'" />
      <CirclePlusFilled v-if="props.class === 'CirclePlusFilled'" />
      <Clock v-if="props.class === 'Clock'" />
      <Close v-if="props.class === 'Close'" />
      <CloseBold v-if="props.class === 'CloseBold'" />
      <Cloudy v-if="props.class === 'Cloudy'" />
      <Coffee v-if="props.class === 'Coffee'" />
      <CoffeeCup v-if="props.class === 'CoffeeCup'" />
      <Coin v-if="props.class === 'Coin'" />
      <ColdDrink v-if="props.class === 'ColdDrink'" />
      <Collection v-if="props.class === 'Collection'" />
      <CollectionTag v-if="props.class === 'CollectionTag'" />
      <Comment v-if="props.class === 'Comment'" />
      <Compass v-if="props.class === 'Compass'" />
      <Connection v-if="props.class === 'Connection'" />
      <Coordinate v-if="props.class === 'Coordinate'" />
      <CopyDocument v-if="props.class === 'CopyDocument'" />
      <Cpu v-if="props.class === 'Cpu'" />
      <CreditCard v-if="props.class === 'CreditCard'" />
      <Crop v-if="props.class === 'Crop'" />
      <DArrowLeft v-if="props.class === 'DArrowLeft'" />
      <DArrowRight v-if="props.class === 'DArrowRight'" />
      <DCaret v-if="props.class === 'DCaret'" />
      <DataAnalysis v-if="props.class === 'DataAnalysis'" />
      <DataBoard v-if="props.class === 'DataBoard'" />
      <DataLine v-if="props.class === 'DataLine'" />
      <Delete v-if="props.class === 'Delete'" />
      <DeleteFilled v-if="props.class === 'DeleteFilled'" />
      <DeleteLocation v-if="props.class === 'DeleteLocation'" />
      <Dessert v-if="props.class === 'Dessert'" />
      <Discount v-if="props.class === 'Discount'" />
      <Dish v-if="props.class === 'Dish'" />
      <DishDot v-if="props.class === 'DishDot'" />
      <Document v-if="props.class === 'Document'" />
      <DocumentAdd v-if="props.class === 'DocumentAdd'" />
      <DocumentChecked v-if="props.class === 'DocumentChecked'" />
      <DocumentCopy v-if="props.class === 'DocumentCopy'" />
      <DocumentDelete v-if="props.class === 'DocumentDelete'" />
      <DocumentRemove v-if="props.class === 'DocumentRemove'" />
      <Download v-if="props.class === 'Download'" />
      <Drizzling v-if="props.class === 'Drizzling'" />
      <Edit v-if="props.class === 'Edit'" />
      <EditPen v-if="props.class === 'EditPen'" />
      <Eleme v-if="props.class === 'Eleme'" />
      <ElemeFilled v-if="props.class === 'ElemeFilled'" />
      <ElementPlus v-if="props.class === 'ElementPlus'" />
      <Expand v-if="props.class === 'Expand'" />
      <Failed v-if="props.class === 'Failed'" />
      <Female v-if="props.class === 'Female'" />
      <Files v-if="props.class === 'Files'" />
      <Film v-if="props.class === 'Film'" />
      <Filter v-if="props.class === 'Filter'" />
      <Finished v-if="props.class === 'Finished'" />
      <FirstAidKit v-if="props.class === 'FirstAidKit'" />
      <Flag v-if="props.class === 'Flag'" />
      <Fold v-if="props.class === 'Fold'" />
      <Folder v-if="props.class === 'Folder'" />
      <FolderAdd v-if="props.class === 'FolderAdd'" />
      <FolderChecked v-if="props.class === 'FolderChecked'" />
      <FolderDelete v-if="props.class === 'FolderDelete'" />
      <FolderOpened v-if="props.class === 'FolderOpened'" />
      <FolderRemove v-if="props.class === 'FolderRemove'" />
      <Food v-if="props.class === 'Food'" />
      <Football v-if="props.class === 'Football'" />
      <ForkSpoon v-if="props.class === 'ForkSpoon'" />
      <Fries v-if="props.class === 'Fries'" />
      <FullScreen v-if="props.class === 'FullScreen'" />
      <Goblet v-if="props.class === 'Goblet'" />
      <GobletFull v-if="props.class === 'GobletFull'" />
      <GobletSquare v-if="props.class === 'GobletSquare'" />
      <GobletSquareFull v-if="props.class === 'GobletSquareFull'" />
      <Goods v-if="props.class === 'Goods'" />
      <GoodsFilled v-if="props.class === 'GoodsFilled'" />
      <Grape v-if="props.class === 'Grape'" />
      <Grid v-if="props.class === 'Grid'" />
      <Guide v-if="props.class === 'Guide'" />
      <Headset v-if="props.class === 'Headset'" />
      <Help v-if="props.class === 'Help'" />
      <HelpFilled v-if="props.class === 'HelpFilled'" />
      <Hide v-if="props.class === 'Hide'" />
      <Histogram v-if="props.class === 'Histogram'" />
      <HomeFilled v-if="props.class === 'HomeFilled'" />
      <HotWater v-if="props.class === 'HotWater'" />
      <House v-if="props.class === 'House'" />
      <IceCream v-if="props.class === 'IceCream'" />
      <IceCreamRound v-if="props.class === 'IceCreamRound'" />
      <IceCreamSquare v-if="props.class === 'IceCreamSquare'" />
      <IceDrink v-if="props.class === 'IceDrink'" />
      <IceTea v-if="props.class === 'IceTea'" />
      <InfoFilled v-if="props.class === 'InfoFilled'" />
      <Iphone v-if="props.class === 'Iphone'" />
      <Key v-if="props.class === 'Key'" />
      <KnifeFork v-if="props.class === 'KnifeFork'" />
      <Lightning v-if="props.class === 'Lightning'" />
      <Link v-if="props.class === 'Link'" />
      <List v-if="props.class === 'List'" />
      <Loading v-if="props.class === 'Loading'" />
      <Location v-if="props.class === 'Location'" />
      <LocationFilled v-if="props.class === 'LocationFilled'" />
      <LocationInformation v-if="props.class === 'LocationInformation'" />
      <Lock v-if="props.class === 'Lock'" />
      <Lollipop v-if="props.class === 'Lollipop'" />
      <MagicStick v-if="props.class === 'MagicStick'" />
      <Magnet v-if="props.class === 'Magnet'" />
      <Male v-if="props.class === 'Male'" />
      <Management v-if="props.class === 'Management'" />
      <MapLocation v-if="props.class === 'MapLocation'" />
      <Medal v-if="props.class === 'Medal'" />
      <Menu v-if="props.class === 'Menu'" />
      <Message v-if="props.class === 'Message'" />
      <MessageBox v-if="props.class === 'MessageBox'" />
      <Mic v-if="props.class === 'Mic'" />
      <Microphone v-if="props.class === 'Microphone'" />
      <MilkTea v-if="props.class === 'MilkTea'" />
      <Minus v-if="props.class === 'Minus'" />
      <Money v-if="props.class === 'Money'" />
      <Monitor v-if="props.class === 'Monitor'" />
      <Moon v-if="props.class === 'Moon'" />
      <MoonNight v-if="props.class === 'MoonNight'" />
      <More v-if="props.class === 'More'" />
      <MoreFilled v-if="props.class === 'MoreFilled'" />
      <MostlyCloudy v-if="props.class === 'MostlyCloudy'" />
      <Mouse v-if="props.class === 'Mouse'" />
      <Mug v-if="props.class === 'Mug'" />
      <Mute v-if="props.class === 'Mute'" />
      <MuteNotification v-if="props.class === 'MuteNotification'" />
      <NoSmoking v-if="props.class === 'NoSmoking'" />
      <Notebook v-if="props.class === 'Notebook'" />
      <Notification v-if="props.class === 'Notification'" />
      <Odometer v-if="props.class === 'Odometer'" />
      <OfficeBuilding v-if="props.class === 'OfficeBuilding'" />
      <Open v-if="props.class === 'Open'" />
      <Operation v-if="props.class === 'Operation'" />
      <Opportunity v-if="props.class === 'Opportunity'" />
      <Orange v-if="props.class === 'Orange'" />
      <Paperclip v-if="props.class === 'Paperclip'" />
      <PartlyCloudy v-if="props.class === 'PartlyCloudy'" />
      <Pear v-if="props.class === 'Pear'" />
      <Phone v-if="props.class === 'Phone'" />
      <PhoneFilled v-if="props.class === 'PhoneFilled'" />
      <Picture v-if="props.class === 'Picture'" />
      <PictureFilled v-if="props.class === 'PictureFilled'" />
      <PictureRounded v-if="props.class === 'PictureRounded'" />
      <PieChart v-if="props.class === 'PieChart'" />
      <Place v-if="props.class === 'Place'" />
      <Platform v-if="props.class === 'Platform'" />
      <Plus v-if="props.class === 'Plus'" />
      <Pointer v-if="props.class === 'Pointer'" />
      <Position v-if="props.class === 'Position'" />
      <Postcard v-if="props.class === 'Postcard'" />
      <Pouring v-if="props.class === 'Pouring'" />
      <Present v-if="props.class === 'Present'" />
      <PriceTag v-if="props.class === 'PriceTag'" />
      <Printer v-if="props.class === 'Printer'" />
      <Promotion v-if="props.class === 'Promotion'" />
      <QuestionFilled v-if="props.class === 'QuestionFilled'" />
      <Rank v-if="props.class === 'Rank'" />
      <Reading v-if="props.class === 'Reading'" />
      <ReadingLamp v-if="props.class === 'ReadingLamp'" />
      <Refresh v-if="props.class === 'Refresh'" />
      <RefreshLeft v-if="props.class === 'RefreshLeft'" />
      <RefreshRight v-if="props.class === 'RefreshRight'" />
      <Refrigerator v-if="props.class === 'Refrigerator'" />
      <Remove v-if="props.class === 'Remove'" />
      <RemoveFilled v-if="props.class === 'RemoveFilled'" />
      <Right v-if="props.class === 'Right'" />
      <ScaleToOriginal v-if="props.class === 'ScaleToOriginal'" />
      <School v-if="props.class === 'School'" />
      <Scissor v-if="props.class === 'Scissor'" />
      <Search v-if="props.class === 'Search'" />
      <Select v-if="props.class === 'Select'" />
      <Sell v-if="props.class === 'Sell'" />
      <SemiSelect v-if="props.class === 'SemiSelect'" />
      <Service v-if="props.class === 'Service'" />
      <SetUp v-if="props.class === 'SetUp'" />
      <Setting v-if="props.class === 'Setting'" />
      <Share v-if="props.class === 'Share'" />
      <Ship v-if="props.class === 'Ship'" />
      <Shop v-if="props.class === 'Shop'" />
      <ShoppingBag v-if="props.class === 'ShoppingBag'" />
      <ShoppingCart v-if="props.class === 'ShoppingCart'" />
      <ShoppingCartFull v-if="props.class === 'ShoppingCartFull'" />
      <Smoking v-if="props.class === 'Smoking'" />
      <Soccer v-if="props.class === 'Soccer'" />
      <SoldOut v-if="props.class === 'SoldOut'" />
      <Sort v-if="props.class === 'Sort'" />
      <SortDown v-if="props.class === 'SortDown'" />
      <SortUp v-if="props.class === 'SortUp'" />
      <Stamp v-if="props.class === 'Stamp'" />
      <Star v-if="props.class === 'Star'" />
      <StarFilled v-if="props.class === 'StarFilled'" />
      <Stopwatch v-if="props.class === 'Stopwatch'" />
      <SuccessFilled v-if="props.class === 'SuccessFilled'" />
      <Sugar v-if="props.class === 'Sugar'" />
      <Suitcase v-if="props.class === 'Suitcase'" />
      <Sunny v-if="props.class === 'Sunny'" />
      <Sunrise v-if="props.class === 'Sunrise'" />
      <Sunset v-if="props.class === 'Sunset'" />
      <Switch v-if="props.class === 'Switch'" />
      <SwitchButton v-if="props.class === 'SwitchButton'" />
      <TakeawayBox v-if="props.class === 'TakeawayBox'" />
      <Ticket v-if="props.class === 'Ticket'" />
      <Tickets v-if="props.class === 'Tickets'" />
      <Timer v-if="props.class === 'Timer'" />
      <ToiletPaper v-if="props.class === 'ToiletPaper'" />
      <Tools v-if="props.class === 'Tools'" />
      <Top v-if="props.class === 'Top'" />
      <TopLeft v-if="props.class === 'TopLeft'" />
      <TopRight v-if="props.class === 'TopRight'" />
      <TrendCharts v-if="props.class === 'TrendCharts'" />
      <Trophy v-if="props.class === 'Trophy'" />
      <TurnOff v-if="props.class === 'TurnOff'" />
      <Umbrella v-if="props.class === 'Umbrella'" />
      <Unlock v-if="props.class === 'Unlock'" />
      <Upload v-if="props.class === 'Upload'" />
      <UploadFilled v-if="props.class === 'UploadFilled'" />
      <User v-if="props.class === 'User'" />
      <UserFilled v-if="props.class === 'UserFilled'" />
      <Van v-if="props.class === 'Van'" />
      <VideoCamera v-if="props.class === 'VideoCamera'" />
      <VideoCameraFilled v-if="props.class === 'VideoCameraFilled'" />
      <VideoPause v-if="props.class === 'VideoPause'" />
      <VideoPlay v-if="props.class === 'VideoPlay'" />
      <View v-if="props.class === 'View'" />
      <Wallet v-if="props.class === 'Wallet'" />
      <WalletFilled v-if="props.class === 'WalletFilled'" />
      <Warning v-if="props.class === 'Warning'" />
      <WarningFilled v-if="props.class === 'WarningFilled'" />
      <Watch v-if="props.class === 'Watch'" />
      <Watermelon v-if="props.class === 'Watermelon'" />
      <WindPower v-if="props.class === 'WindPower'" />
      <ZoomIn v-if="props.class === 'ZoomIn'" />
      <ZoomOut v-if="props.class === 'ZoomOut'" />
    </el-icon>
  </div>
</template>

<script setup>
import { computed, ref, watch, unref, watchEffect, reactive, onMounted, nextTick, useAttrs, useSlots } from 'vue';
import { ElInput, ElIcon, ElInputNumber } from 'element-plus';
import { AddLocation, Aim, AlarmClock, Apple, ArrowDown, ArrowDownBold, ArrowLeft, ArrowLeftBold, ArrowRight, ArrowRightBold, ArrowUp, ArrowUpBold, Avatar, Back, Baseball, Basketball, Bell, BellFilled, Bicycle, Bottom, BottomLeft, BottomRight, Bowl, Box, Briefcase, Brush, BrushFilled, Burger, Calendar, Camera, CameraFilled, CaretBottom, CaretLeft, CaretRight, CaretTop, Cellphone, ChatDotRound, ChatDotSquare, ChatLineRound, ChatLineSquare, ChatRound, ChatSquare, Check, Checked, Cherry, Chicken, CircleCheck, CircleCheckFilled, CircleClose, CircleCloseFilled, CirclePlus, CirclePlusFilled, Clock, Close, CloseBold, Cloudy, Coffee, CoffeeCup, Coin, ColdDrink, Collection, CollectionTag, Comment, Compass, Connection, Coordinate, CopyDocument, Cpu, CreditCard, Crop, DArrowLeft, DArrowRight, DCaret, DataAnalysis, DataBoard, DataLine, Delete, DeleteFilled, DeleteLocation, Dessert, Discount, Dish, DishDot, Document, DocumentAdd, DocumentChecked, DocumentCopy, DocumentDelete, DocumentRemove, Download, Drizzling, Edit, EditPen, Eleme, ElemeFilled, ElementPlus, Expand, Failed, Female, Files, Film, Filter, Finished, FirstAidKit, Flag, Fold, Folder, FolderAdd, FolderChecked, FolderDelete, FolderOpened, FolderRemove, Food, Football, ForkSpoon, Fries, FullScreen, Goblet, GobletFull, GobletSquare, GobletSquareFull, Goods, GoodsFilled, Grape, Grid, Guide, Headset, Help, HelpFilled, Hide, Histogram, HomeFilled, HotWater, House, IceCream, IceCreamRound, IceCreamSquare, IceDrink, IceTea, InfoFilled, Iphone, Key, KnifeFork, Lightning, Link, List, Loading, Location, LocationFilled, LocationInformation, Lock, Lollipop, MagicStick, Magnet, Male, Management, MapLocation, Medal, Menu, Message, MessageBox, Mic, Microphone, MilkTea, Minus, Money, Monitor, Moon, MoonNight, More, MoreFilled, MostlyCloudy, Mouse, Mug, Mute, MuteNotification, NoSmoking, Notebook, Notification, Odometer, OfficeBuilding, Open, Operation, Opportunity, Orange, Paperclip, PartlyCloudy, Pear, Phone, PhoneFilled, Picture, PictureFilled, PictureRounded, PieChart, Place, Platform, Plus, Pointer, Position, Postcard, Pouring, Present, PriceTag, Printer, Promotion, QuestionFilled, Rank, Reading, ReadingLamp, Refresh, RefreshLeft, RefreshRight, Refrigerator, Remove, RemoveFilled, Right, ScaleToOriginal, School, Scissor, Search, Select, Sell, SemiSelect, Service, SetUp, Setting, Share, Ship, Shop, ShoppingBag, ShoppingCart, ShoppingCartFull, Smoking, Soccer, SoldOut, Sort, SortDown, SortUp, Stamp, Star, StarFilled, Stopwatch, SuccessFilled, Sugar, Suitcase, Sunny, Sunrise, Sunset, Switch, SwitchButton, TakeawayBox, Ticket, Tickets, Timer, ToiletPaper, Tools, Top, TopLeft, TopRight, TrendCharts, Trophy, TurnOff, Umbrella, Unlock, Upload, UploadFilled, User, UserFilled, Van, VideoCamera, VideoCameraFilled, VideoPause, VideoPlay, View, Wallet, WalletFilled, Warning, WarningFilled, Watch, Watermelon, WindPower, ZoomIn, ZoomOut } from '@element-plus/icons-vue';

const props = defineProps({
  size: { type: Number, default: () => { return 16; } },
  color: { type: String, default: () => { return '#0E1D38'; } },
  class: { type: String, default: () => { return ''; } }
});

</script>

<style lang="less" scoped>
.d-icon {
  width: auto;
}
</style>